// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PlateArchive.Data;

#nullable disable

namespace PlateArchive.Data.Migrations
{
    [DbContext(typeof(PlateArchiveDbContext))]
    [Migration("20260625180000_RinominaFamiglieInFormatiAddFormatoPiastra")]
    partial class RinominaFamiglieInFormatiAddFormatoPiastra
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PlateArchive.Core.Models.CategoriaPiastra", b =>
                {
                    b.Property<int>("IdCategoriaPiastra").ValueGeneratedOnAdd().HasColumnType("int");
                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCategoriaPiastra"));
                    b.Property<string>("Codice").IsRequired().HasColumnType("nvarchar(450)");
                    b.Property<string>("Descrizione").IsRequired().HasColumnType("nvarchar(max)");
                    b.Property<int>("Ordine").HasColumnType("int");
                    b.HasKey("IdCategoriaPiastra");
                    b.HasIndex("Codice").IsUnique();
                    b.ToTable("CategoriePiastre");
                });

            modelBuilder.Entity("PlateArchive.Core.Models.Cliente", b =>
                {
                    b.Property<int>("IdCliente").ValueGeneratedOnAdd().HasColumnType("int");
                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCliente"));
                    b.Property<string>("CodiceClienteGestionale").IsRequired().HasColumnType("nvarchar(450)");
                    b.Property<string>("Note").HasColumnType("nvarchar(max)");
                    b.Property<string>("RagioneSociale").IsRequired().HasColumnType("nvarchar(max)");
                    b.HasKey("IdCliente");
                    b.HasIndex("CodiceClienteGestionale").IsUnique();
                    b.ToTable("Clienti");
                });

            modelBuilder.Entity("PlateArchive.Core.Models.ClienteMacchina", b =>
                {
                    b.Property<int>("IdClienteMacchina").ValueGeneratedOnAdd().HasColumnType("int");
                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdClienteMacchina"));
                    b.Property<bool>("Attiva").HasColumnType("bit");
                    b.Property<string>("CodiceInternoCliente").HasColumnType("nvarchar(max)");
                    b.Property<DateTime>("DataAssociazione").HasColumnType("datetime2");
                    b.Property<int>("IdCliente").HasColumnType("int");
                    b.Property<int>("IdMacchinaStandard").HasColumnType("int");
                    b.Property<string>("Matricola").HasColumnType("nvarchar(max)");
                    b.Property<string>("Note").HasColumnType("nvarchar(max)");
                    b.HasKey("IdClienteMacchina");
                    b.HasIndex("IdCliente");
                    b.HasIndex("IdMacchinaStandard");
                    b.ToTable("ClientiMacchine");
                });

            modelBuilder.Entity("PlateArchive.Core.Models.ClientePiastra", b =>
                {
                    b.Property<int>("IdClientePiastra").ValueGeneratedOnAdd().HasColumnType("int");
                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdClientePiastra"));
                    b.Property<DateTime>("DataAssociazione").HasColumnType("datetime2");
                    b.Property<int>("IdCliente").HasColumnType("int");
                    b.Property<int?>("IdClienteMacchina").HasColumnType("int");
                    b.Property<int>("IdPiastra").HasColumnType("int");
                    b.Property<string>("Note").HasColumnType("nvarchar(max)");
                    b.Property<int>("Stato").HasColumnType("int");
                    b.HasKey("IdClientePiastra");
                    b.HasIndex("IdCliente");
                    b.HasIndex("IdClienteMacchina");
                    b.HasIndex("IdPiastra");
                    b.HasIndex("IdCliente", "IdPiastra").IsUnique();
                    b.ToTable("ClientiPiastre");
                });

            modelBuilder.Entity("PlateArchive.Core.Models.Disegno", b =>
                {
                    b.Property<int>("IdDisegno").ValueGeneratedOnAdd().HasColumnType("int");
                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdDisegno"));
                    b.Property<string>("CodiceDisegno").HasColumnType("nvarchar(max)");
                    b.Property<DateTime?>("DataUltimaModificaFile").HasColumnType("datetime2");
                    b.Property<string>("Formato").HasColumnType("nvarchar(max)");
                    b.Property<int>("IdPiastra").HasColumnType("int");
                    b.Property<string>("NomeFile").HasColumnType("nvarchar(max)");
                    b.Property<string>("Note").HasColumnType("nvarchar(max)");
                    b.Property<string>("PercorsoFile").HasColumnType("nvarchar(max)");
                    b.Property<string>("Revisione").HasColumnType("nvarchar(max)");
                    b.Property<int>("Stato").HasColumnType("int");
                    b.Property<string>("VaultId").HasColumnType("nvarchar(max)");
                    b.HasKey("IdDisegno");
                    b.HasIndex("IdPiastra").IsUnique();
                    b.ToTable("Disegni");
                });

            modelBuilder.Entity("PlateArchive.Core.Models.FormatoMacchina", b =>
                {
                    b.Property<int>("IdFormato").ValueGeneratedOnAdd().HasColumnType("int");
                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdFormato"));
                    b.Property<bool>("IsEliminata").HasColumnType("bit");
                    b.Property<string>("NomeFormato").IsRequired().HasColumnType("nvarchar(450)");
                    b.Property<string>("Note").HasColumnType("nvarchar(max)");
                    b.HasKey("IdFormato");
                    b.HasIndex("NomeFormato").IsUnique();
                    b.ToTable("FormatiMacchine");
                });

            modelBuilder.Entity("PlateArchive.Core.Models.MacchinaStandard", b =>
                {
                    b.Property<int>("IdMacchinaStandard").ValueGeneratedOnAdd().HasColumnType("int");
                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdMacchinaStandard"));
                    b.Property<decimal?>("AltezzaMm").HasColumnType("decimal(18,2)");
                    b.Property<bool>("Attiva").HasColumnType("bit");
                    b.Property<string>("CodiceMacchina").IsRequired().HasColumnType("nvarchar(450)");
                    b.Property<int?>("IdFormato").HasColumnType("int");
                    b.Property<int?>("IdProduttore").HasColumnType("int");
                    b.Property<decimal?>("LarghezzaMm").HasColumnType("decimal(18,2)");
                    b.Property<string>("NomeMacchina").IsRequired().HasColumnType("nvarchar(max)");
                    b.Property<string>("Note").HasColumnType("nvarchar(max)");
                    b.Property<string>("Versione").HasColumnType("nvarchar(max)");
                    b.HasKey("IdMacchinaStandard");
                    b.HasIndex("CodiceMacchina").IsUnique();
                    b.HasIndex("IdFormato");
                    b.HasIndex("IdProduttore");
                    b.ToTable("MacchineStandard");
                });

            modelBuilder.Entity("PlateArchive.Core.Models.Piastra", b =>
                {
                    b.Property<int>("IdPiastra").ValueGeneratedOnAdd().HasColumnType("int");
                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPiastra"));
                    b.Property<decimal?>("AltezzaMm").HasColumnType("decimal(18,2)");
                    b.Property<string>("CodiceArticoloGestionale").HasColumnType("nvarchar(450)");
                    b.Property<string>("CodicePiastra").IsRequired().HasColumnType("nvarchar(450)");
                    b.Property<DateTime>("DataCreazione").HasColumnType("datetime2");
                    b.Property<DateTime>("DataUltimaModifica").HasColumnType("datetime2");
                    b.Property<string>("Descrizione").HasColumnType("nvarchar(max)");
                    b.Property<decimal?>("Durezza").HasColumnType("decimal(18,2)");
                    b.Property<int?>("IdCategoriaPiastra").HasColumnType("int");
                    b.Property<int?>("IdFormato").HasColumnType("int");
                    b.Property<bool>("IsEliminata").HasColumnType("bit");
                    b.Property<decimal?>("LarghezzaMm").HasColumnType("decimal(18,2)");
                    b.Property<string>("Note").HasColumnType("nvarchar(max)");
                    b.Property<decimal?>("Peso").HasColumnType("decimal(18,3)");
                    b.Property<decimal?>("SpessoreMm").HasColumnType("decimal(18,2)");
                    b.Property<int>("Stato").HasColumnType("int");
                    b.HasKey("IdPiastra");
                    b.HasIndex("CodiceArticoloGestionale").IsUnique().HasFilter("[CodiceArticoloGestionale] IS NOT NULL");
                    b.HasIndex("CodicePiastra").IsUnique();
                    b.HasIndex("IdCategoriaPiastra");
                    b.HasIndex("IdFormato");
                    b.ToTable("Piastre");
                });

            modelBuilder.Entity("PlateArchive.Core.Models.PiastraMacchinaCompatibile", b =>
                {
                    b.Property<int>("IdCompatibilita").ValueGeneratedOnAdd().HasColumnType("int");
                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCompatibilita"));
                    b.Property<bool>("Attiva").HasColumnType("bit");
                    b.Property<DateTime?>("DataVerifica").HasColumnType("datetime2");
                    b.Property<int?>("FonteDato").HasColumnType("int");
                    b.Property<int>("IdMacchinaStandard").HasColumnType("int");
                    b.Property<int>("IdPiastra").HasColumnType("int");
                    b.Property<string>("Note").HasColumnType("nvarchar(max)");
                    b.Property<string>("UtenteVerifica").HasColumnType("nvarchar(max)");
                    b.HasKey("IdCompatibilita");
                    b.HasIndex("IdMacchinaStandard");
                    b.HasIndex("IdPiastra");
                    b.HasIndex("IdPiastra", "IdMacchinaStandard").IsUnique();
                    b.ToTable("PiastreMacchineCompatibili");
                });

            modelBuilder.Entity("PlateArchive.Core.Models.ProduttoreMacchina", b =>
                {
                    b.Property<int>("IdProduttore").ValueGeneratedOnAdd().HasColumnType("int");
                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdProduttore"));
                    b.Property<bool>("IsEliminata").HasColumnType("bit");
                    b.Property<string>("NomeProduttore").IsRequired().HasColumnType("nvarchar(450)");
                    b.Property<string>("Note").HasColumnType("nvarchar(max)");
                    b.HasKey("IdProduttore");
                    b.HasIndex("NomeProduttore").IsUnique();
                    b.ToTable("ProduttoriMacchine");
                });

            // ─── Relazioni ────────────────────────────────────────────────

            modelBuilder.Entity("PlateArchive.Core.Models.ClienteMacchina", b =>
                {
                    b.HasOne("PlateArchive.Core.Models.Cliente", "Cliente")
                        .WithMany("Macchine").HasForeignKey("IdCliente")
                        .OnDelete(DeleteBehavior.Cascade).IsRequired();
                    b.HasOne("PlateArchive.Core.Models.MacchinaStandard", "MacchinaStandard")
                        .WithMany("ClientiAssociati").HasForeignKey("IdMacchinaStandard")
                        .OnDelete(DeleteBehavior.Cascade).IsRequired();
                    b.Navigation("Cliente");
                    b.Navigation("MacchinaStandard");
                });

            modelBuilder.Entity("PlateArchive.Core.Models.ClientePiastra", b =>
                {
                    b.HasOne("PlateArchive.Core.Models.Cliente", "Cliente")
                        .WithMany("Piastre").HasForeignKey("IdCliente")
                        .OnDelete(DeleteBehavior.Cascade).IsRequired();
                    b.HasOne("PlateArchive.Core.Models.ClienteMacchina", "ClienteMacchina")
                        .WithMany().HasForeignKey("IdClienteMacchina")
                        .OnDelete(DeleteBehavior.SetNull);
                    b.HasOne("PlateArchive.Core.Models.Piastra", "Piastra")
                        .WithMany("ClientiAssociati").HasForeignKey("IdPiastra")
                        .OnDelete(DeleteBehavior.Cascade).IsRequired();
                    b.Navigation("Cliente");
                    b.Navigation("ClienteMacchina");
                    b.Navigation("Piastra");
                });

            modelBuilder.Entity("PlateArchive.Core.Models.Disegno", b =>
                {
                    b.HasOne("PlateArchive.Core.Models.Piastra", "Piastra")
                        .WithOne("Disegno")
                        .HasForeignKey("PlateArchive.Core.Models.Disegno", "IdPiastra")
                        .OnDelete(DeleteBehavior.Cascade).IsRequired();
                    b.Navigation("Piastra");
                });

            modelBuilder.Entity("PlateArchive.Core.Models.MacchinaStandard", b =>
                {
                    b.HasOne("PlateArchive.Core.Models.FormatoMacchina", "Formato")
                        .WithMany("Macchine").HasForeignKey("IdFormato")
                        .OnDelete(DeleteBehavior.SetNull);
                    b.HasOne("PlateArchive.Core.Models.ProduttoreMacchina", "Produttore")
                        .WithMany("Macchine").HasForeignKey("IdProduttore")
                        .OnDelete(DeleteBehavior.SetNull);
                    b.Navigation("Formato");
                    b.Navigation("Produttore");
                });

            modelBuilder.Entity("PlateArchive.Core.Models.Piastra", b =>
                {
                    b.HasOne("PlateArchive.Core.Models.CategoriaPiastra", "Categoria")
                        .WithMany().HasForeignKey("IdCategoriaPiastra")
                        .OnDelete(DeleteBehavior.SetNull);
                    b.HasOne("PlateArchive.Core.Models.FormatoMacchina", "Formato")
                        .WithMany("Piastre").HasForeignKey("IdFormato")
                        .OnDelete(DeleteBehavior.SetNull);
                    b.Navigation("Categoria");
                    b.Navigation("Formato");
                });

            modelBuilder.Entity("PlateArchive.Core.Models.PiastraMacchinaCompatibile", b =>
                {
                    b.HasOne("PlateArchive.Core.Models.MacchinaStandard", "MacchinaStandard")
                        .WithMany("PiastreCompatibili").HasForeignKey("IdMacchinaStandard")
                        .OnDelete(DeleteBehavior.Cascade).IsRequired();
                    b.HasOne("PlateArchive.Core.Models.Piastra", "Piastra")
                        .WithMany("MacchineCompatibili").HasForeignKey("IdPiastra")
                        .OnDelete(DeleteBehavior.Cascade).IsRequired();
                    b.Navigation("MacchinaStandard");
                    b.Navigation("Piastra");
                });

            modelBuilder.Entity("PlateArchive.Core.Models.Cliente", b =>
                {
                    b.Navigation("Macchine");
                    b.Navigation("Piastre");
                });

            modelBuilder.Entity("PlateArchive.Core.Models.FormatoMacchina", b =>
                {
                    b.Navigation("Macchine");
                    b.Navigation("Piastre");
                });

            modelBuilder.Entity("PlateArchive.Core.Models.MacchinaStandard", b =>
                {
                    b.Navigation("ClientiAssociati");
                    b.Navigation("PiastreCompatibili");
                });

            modelBuilder.Entity("PlateArchive.Core.Models.Piastra", b =>
                {
                    b.Navigation("Categoria");
                    b.Navigation("ClientiAssociati");
                    b.Navigation("Disegno");
                    b.Navigation("Formato");
                    b.Navigation("MacchineCompatibili");
                });

            modelBuilder.Entity("PlateArchive.Core.Models.ProduttoreMacchina", b =>
                {
                    b.Navigation("Macchine");
                });
#pragma warning restore 612, 618
        }
    }
}
