// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PlateArchive.Data;

#nullable disable

namespace PlateArchive.Data.Migrations
{
    [DbContext(typeof(PlateArchiveDbContext))]
    [Migration("20260623150243_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("PlateArchive.Core.Models.Cliente", b =>
                {
                    b.Property<int>("IdCliente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CodiceClienteGestionale")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CodiceFiscale")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DataUltimaSincronizzazione")
                        .HasColumnType("TEXT");

                    b.Property<string>("Note")
                        .HasColumnType("TEXT");

                    b.Property<string>("PartitaIVA")
                        .HasColumnType("TEXT");

                    b.Property<string>("RagioneSociale")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("StatoCliente")
                        .HasColumnType("INTEGER");

                    b.HasKey("IdCliente");

                    b.HasIndex("CodiceClienteGestionale")
                        .IsUnique();

                    b.ToTable("Clienti");
                });

            modelBuilder.Entity("PlateArchive.Core.Models.ClienteMacchina", b =>
                {
                    b.Property<int>("IdClienteMacchina")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Attiva")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ClienteIdCliente")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CodiceInternoCliente")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataAssociazione")
                        .HasColumnType("TEXT");

                    b.Property<int>("IdCliente")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IdMacchinaStandard")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MacchinaStandardIdMacchinaStandard")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Matricola")
                        .HasColumnType("TEXT");

                    b.Property<string>("Note")
                        .HasColumnType("TEXT");

                    b.HasKey("IdClienteMacchina");

                    b.HasIndex("ClienteIdCliente");

                    b.HasIndex("MacchinaStandardIdMacchinaStandard");

                    b.ToTable("ClientiMacchine");
                });

            modelBuilder.Entity("PlateArchive.Core.Models.ClientePiastra", b =>
                {
                    b.Property<int>("IdClientePiastra")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ClienteIdCliente")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DataAssociazione")
                        .HasColumnType("TEXT");

                    b.Property<int>("IdCliente")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("IdClienteMacchina")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IdPiastra")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Note")
                        .HasColumnType("TEXT");

                    b.Property<int>("PiastraIdPiastra")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Stato")
                        .HasColumnType("INTEGER");

                    b.HasKey("IdClientePiastra");

                    b.HasIndex("ClienteIdCliente");

                    b.HasIndex("IdClienteMacchina");

                    b.HasIndex("PiastraIdPiastra");

                    b.HasIndex("IdCliente", "IdPiastra")
                        .IsUnique();

                    b.ToTable("ClientiPiastre");
                });

            modelBuilder.Entity("PlateArchive.Core.Models.Disegno", b =>
                {
                    b.Property<int>("IdDisegno")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CodiceDisegno")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DataUltimaModificaFile")
                        .HasColumnType("TEXT");

                    b.Property<string>("Formato")
                        .HasColumnType("TEXT");

                    b.Property<int>("IdPiastra")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NomeFile")
                        .HasColumnType("TEXT");

                    b.Property<string>("Note")
                        .HasColumnType("TEXT");

                    b.Property<string>("PercorsoFile")
                        .HasColumnType("TEXT");

                    b.Property<string>("Revisione")
                        .HasColumnType("TEXT");

                    b.Property<int>("Stato")
                        .HasColumnType("INTEGER");

                    b.Property<string>("VaultId")
                        .HasColumnType("TEXT");

                    b.HasKey("IdDisegno");

                    b.HasIndex("IdPiastra")
                        .IsUnique();

                    b.ToTable("Disegni");
                });

            modelBuilder.Entity("PlateArchive.Core.Models.MacchinaStandard", b =>
                {
                    b.Property<int>("IdMacchinaStandard")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Attiva")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CodiceMacchina")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Famiglia")
                        .HasColumnType("TEXT");

                    b.Property<string>("Formato")
                        .HasColumnType("TEXT");

                    b.Property<string>("NomeMacchina")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Note")
                        .HasColumnType("TEXT");

                    b.Property<string>("Produttore")
                        .HasColumnType("TEXT");

                    b.Property<string>("Versione")
                        .HasColumnType("TEXT");

                    b.HasKey("IdMacchinaStandard");

                    b.HasIndex("CodiceMacchina")
                        .IsUnique();

                    b.ToTable("MacchineStandard");
                });

            modelBuilder.Entity("PlateArchive.Core.Models.Piastra", b =>
                {
                    b.Property<int>("IdPiastra")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CodiceArticoloGestionale")
                        .HasColumnType("TEXT");

                    b.Property<string>("CodicePiastra")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataCreazione")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataUltimaModifica")
                        .HasColumnType("TEXT");

                    b.Property<string>("Descrizione")
                        .HasColumnType("TEXT");

                    b.Property<string>("Note")
                        .HasColumnType("TEXT");

                    b.Property<int>("Stato")
                        .HasColumnType("INTEGER");

                    b.HasKey("IdPiastra");

                    b.HasIndex("CodiceArticoloGestionale")
                        .IsUnique()
                        .HasFilter("\"CodiceArticoloGestionale\" IS NOT NULL");

                    b.HasIndex("CodicePiastra")
                        .IsUnique();

                    b.ToTable("Piastre");
                });

            modelBuilder.Entity("PlateArchive.Core.Models.PiastraMacchinaCompatibile", b =>
                {
                    b.Property<int>("IdCompatibilita")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Attiva")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("DataVerifica")
                        .HasColumnType("TEXT");

                    b.Property<int?>("FonteDato")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IdMacchinaStandard")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IdPiastra")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MacchinaStandardIdMacchinaStandard")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Note")
                        .HasColumnType("TEXT");

                    b.Property<int>("PiastraIdPiastra")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UtenteVerifica")
                        .HasColumnType("TEXT");

                    b.HasKey("IdCompatibilita");

                    b.HasIndex("MacchinaStandardIdMacchinaStandard");

                    b.HasIndex("PiastraIdPiastra");

                    b.HasIndex("IdPiastra", "IdMacchinaStandard")
                        .IsUnique();

                    b.ToTable("PiastreMacchineCompatibili");
                });

            modelBuilder.Entity("PlateArchive.Core.Models.ClienteMacchina", b =>
                {
                    b.HasOne("PlateArchive.Core.Models.Cliente", "Cliente")
                        .WithMany("Macchine")
                        .HasForeignKey("ClienteIdCliente")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PlateArchive.Core.Models.MacchinaStandard", "MacchinaStandard")
                        .WithMany("ClientiAssociati")
                        .HasForeignKey("MacchinaStandardIdMacchinaStandard")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");

                    b.Navigation("MacchinaStandard");
                });

            modelBuilder.Entity("PlateArchive.Core.Models.ClientePiastra", b =>
                {
                    b.HasOne("PlateArchive.Core.Models.Cliente", "Cliente")
                        .WithMany("Piastre")
                        .HasForeignKey("ClienteIdCliente")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PlateArchive.Core.Models.ClienteMacchina", "ClienteMacchina")
                        .WithMany()
                        .HasForeignKey("IdClienteMacchina")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("PlateArchive.Core.Models.Piastra", "Piastra")
                        .WithMany("ClientiAssociati")
                        .HasForeignKey("PiastraIdPiastra")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");

                    b.Navigation("ClienteMacchina");

                    b.Navigation("Piastra");
                });

            modelBuilder.Entity("PlateArchive.Core.Models.Disegno", b =>
                {
                    b.HasOne("PlateArchive.Core.Models.Piastra", "Piastra")
                        .WithOne("Disegno")
                        .HasForeignKey("PlateArchive.Core.Models.Disegno", "IdPiastra")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Piastra");
                });

            modelBuilder.Entity("PlateArchive.Core.Models.PiastraMacchinaCompatibile", b =>
                {
                    b.HasOne("PlateArchive.Core.Models.MacchinaStandard", "MacchinaStandard")
                        .WithMany("PiastreCompatibili")
                        .HasForeignKey("MacchinaStandardIdMacchinaStandard")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PlateArchive.Core.Models.Piastra", "Piastra")
                        .WithMany("MacchineCompatibili")
                        .HasForeignKey("PiastraIdPiastra")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MacchinaStandard");

                    b.Navigation("Piastra");
                });

            modelBuilder.Entity("PlateArchive.Core.Models.Cliente", b =>
                {
                    b.Navigation("Macchine");

                    b.Navigation("Piastre");
                });

            modelBuilder.Entity("PlateArchive.Core.Models.MacchinaStandard", b =>
                {
                    b.Navigation("ClientiAssociati");

                    b.Navigation("PiastreCompatibili");
                });

            modelBuilder.Entity("PlateArchive.Core.Models.Piastra", b =>
                {
                    b.Navigation("ClientiAssociati");

                    b.Navigation("Disegno");

                    b.Navigation("MacchineCompatibili");
                });
#pragma warning restore 612, 618
        }
    }
}
