// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PlateArchive.Data;

#nullable disable

namespace PlateArchive.Data.Migrations
{
    [DbContext(typeof(PlateArchiveDbContext))]
    partial class PlateArchiveDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("PlateArchive.Core.Models.CategoriaPiastra", b =>
                {
                    b.Property<int>("IdCategoriaPiastra")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Codice")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Descrizione")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Ordine")
                        .HasColumnType("INTEGER");

                    b.HasKey("IdCategoriaPiastra");

                    b.HasIndex("Codice")
                        .IsUnique();

                    b.ToTable("CategoriePiastre");
                });

            modelBuilder.Entity("PlateArchive.Core.Models.Cliente", b =>
                {
                    b.Property<int>("IdCliente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AttivoGestionale")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CodiceClienteGestionale")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Note")
                        .HasColumnType("TEXT");

                    b.Property<string>("RagioneSociale")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("IdCliente");

                    b.HasIndex("CodiceClienteGestionale")
                        .IsUnique();

                    b.ToTable("Clienti");
                });

            modelBuilder.Entity("PlateArchive.Core.Models.ClienteMacchina", b =>
                {
                    b.Property<int>("IdClienteMacchina")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Attiva")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CodiceInternoCliente")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataAssociazione")
                        .HasColumnType("TEXT");

                    b.Property<int>("IdCliente")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IdMacchinaStandard")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Matricola")
                        .HasColumnType("TEXT");

                    b.Property<string>("Note")
                        .HasColumnType("TEXT");

                    b.HasKey("IdClienteMacchina");

                    b.HasIndex("IdCliente");

                    b.HasIndex("IdMacchinaStandard");

                    b.ToTable("ClientiMacchine");
                });

            modelBuilder.Entity("PlateArchive.Core.Models.ClientePiastra", b =>
                {
                    b.Property<int>("IdClientePiastra")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DataAssociazione")
                        .HasColumnType("TEXT");

                    b.Property<int>("IdCliente")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("IdClienteMacchina")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IdPiastra")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Note")
                        .HasColumnType("TEXT");

                    b.Property<int>("Stato")
                        .HasColumnType("INTEGER");

                    b.HasKey("IdClientePiastra");

                    b.HasIndex("IdClienteMacchina");

                    b.HasIndex("IdPiastra");

                    b.HasIndex("IdCliente", "IdPiastra")
                        .IsUnique();

                    b.ToTable("ClientiPiastre");
                });

            modelBuilder.Entity("PlateArchive.Core.Models.Disegno", b =>
                {
                    b.Property<int>("IdDisegno")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CodiceDisegno")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DataUltimaModificaFile")
                        .HasColumnType("TEXT");

                    b.Property<string>("Formato")
                        .HasColumnType("TEXT");

                    b.Property<int?>("IdPiastra")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NomeFile")
                        .HasColumnType("TEXT");

                    b.Property<string>("Note")
                        .HasColumnType("TEXT");

                    b.Property<string>("PercorsoFile")
                        .HasColumnType("TEXT");

                    b.Property<string>("Revisione")
                        .HasColumnType("TEXT");

                    b.Property<int>("Stato")
                        .HasColumnType("INTEGER");

                    b.Property<string>("VaultId")
                        .HasColumnType("TEXT");

                    b.HasKey("IdDisegno");

                    b.HasIndex("IdPiastra")
                        .IsUnique();

                    b.ToTable("Disegni");
                });

            modelBuilder.Entity("PlateArchive.Core.Models.FormatoMacchina", b =>
                {
                    b.Property<int>("IdFormato")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsEliminata")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NomeFormato")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Note")
                        .HasColumnType("TEXT");

                    b.HasKey("IdFormato");

                    b.ToTable("FormatiMacchine");
                });

            modelBuilder.Entity("PlateArchive.Core.Models.MacchinaStandard", b =>
                {
                    b.Property<int>("IdMacchinaStandard")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("AltezzaMassimaFoglioMm")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("AltezzaMinimaFoglioMm")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Attiva")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CodiceMacchina")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("IdFormato")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("IdProduttore")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("LarghezzaMassimaFoglioMm")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("LarghezzaMinimaFoglioMm")
                        .HasColumnType("TEXT");

                    b.Property<string>("NomeMacchina")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Note")
                        .HasColumnType("TEXT");

                    b.Property<string>("Versione")
                        .HasColumnType("TEXT");

                    b.HasKey("IdMacchinaStandard");

                    b.HasIndex("CodiceMacchina")
                        .IsUnique();

                    b.HasIndex("IdFormato");

                    b.HasIndex("IdProduttore");

                    b.ToTable("MacchineStandard");
                });

            modelBuilder.Entity("PlateArchive.Core.Models.Piastra", b =>
                {
                    b.Property<int>("IdPiastra")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("AltezzaMm")
                        .HasColumnType("TEXT");

                    b.Property<string>("CodiceArticoloGestionale")
                        .HasColumnType("TEXT");

                    b.Property<string>("CodicePiastra")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataCreazione")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataUltimaModifica")
                        .HasColumnType("TEXT");

                    b.Property<string>("Descrizione")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("Durezza")
                        .HasColumnType("TEXT");

                    b.Property<int?>("IdCategoriaPiastra")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("IdClienteEsclusivo")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("IdFormato")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsEliminata")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("LarghezzaMm")
                        .HasColumnType("TEXT");

                    b.Property<string>("Note")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("Peso")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("SpessoreMm")
                        .HasColumnType("TEXT");

                    b.Property<int>("Stato")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TipoPiastra")
                        .HasColumnType("INTEGER");

                    b.HasKey("IdPiastra");

                    b.HasIndex("CodiceArticoloGestionale")
                        .IsUnique()
                        .HasFilter("[CodiceArticoloGestionale] IS NOT NULL");

                    b.HasIndex("CodicePiastra")
                        .IsUnique();

                    b.HasIndex("IdCategoriaPiastra");

                    b.HasIndex("IdClienteEsclusivo");

                    b.HasIndex("IdFormato");

                    b.ToTable("Piastre");
                });

            modelBuilder.Entity("PlateArchive.Core.Models.PiastraMacchinaCompatibile", b =>
                {
                    b.Property<int>("IdCompatibilita")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Attiva")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("DataVerifica")
                        .HasColumnType("TEXT");

                    b.Property<int?>("FonteDato")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IdMacchinaStandard")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IdPiastra")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Note")
                        .HasColumnType("TEXT");

                    b.Property<string>("UtenteVerifica")
                        .HasColumnType("TEXT");

                    b.HasKey("IdCompatibilita");

                    b.HasIndex("IdMacchinaStandard");

                    b.HasIndex("IdPiastra", "IdMacchinaStandard")
                        .IsUnique();

                    b.ToTable("PiastreMacchineCompatibili");
                });

            modelBuilder.Entity("PlateArchive.Core.Models.ProduttoreMacchina", b =>
                {
                    b.Property<int>("IdProduttore")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsEliminata")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NomeProduttore")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Note")
                        .HasColumnType("TEXT");

                    b.HasKey("IdProduttore");

                    b.ToTable("ProduttoriMacchine");
                });

            modelBuilder.Entity("PlateArchive.Core.Models.ClienteMacchina", b =>
                {
                    b.HasOne("PlateArchive.Core.Models.Cliente", "Cliente")
                        .WithMany("Macchine")
                        .HasForeignKey("IdCliente")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PlateArchive.Core.Models.MacchinaStandard", "MacchinaStandard")
                        .WithMany("ClientiAssociati")
                        .HasForeignKey("IdMacchinaStandard")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");

                    b.Navigation("MacchinaStandard");
                });

            modelBuilder.Entity("PlateArchive.Core.Models.ClientePiastra", b =>
                {
                    b.HasOne("PlateArchive.Core.Models.Cliente", "Cliente")
                        .WithMany("Piastre")
                        .HasForeignKey("IdCliente")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PlateArchive.Core.Models.ClienteMacchina", "ClienteMacchina")
                        .WithMany()
                        .HasForeignKey("IdClienteMacchina");

                    b.HasOne("PlateArchive.Core.Models.Piastra", "Piastra")
                        .WithMany("ClientiAssociati")
                        .HasForeignKey("IdPiastra")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");

                    b.Navigation("ClienteMacchina");

                    b.Navigation("Piastra");
                });

            modelBuilder.Entity("PlateArchive.Core.Models.Disegno", b =>
                {
                    b.HasOne("PlateArchive.Core.Models.Piastra", "Piastra")
                        .WithOne("Disegno")
                        .HasForeignKey("PlateArchive.Core.Models.Disegno", "IdPiastra")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Piastra");
                });

            modelBuilder.Entity("PlateArchive.Core.Models.MacchinaStandard", b =>
                {
                    b.HasOne("PlateArchive.Core.Models.FormatoMacchina", "Formato")
                        .WithMany("Macchine")
                        .HasForeignKey("IdFormato");

                    b.HasOne("PlateArchive.Core.Models.ProduttoreMacchina", "Produttore")
                        .WithMany("Macchine")
                        .HasForeignKey("IdProduttore")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Formato");

                    b.Navigation("Produttore");
                });

            modelBuilder.Entity("PlateArchive.Core.Models.Piastra", b =>
                {
                    b.HasOne("PlateArchive.Core.Models.CategoriaPiastra", "Categoria")
                        .WithMany()
                        .HasForeignKey("IdCategoriaPiastra")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("PlateArchive.Core.Models.Cliente", "ClienteEsclusivo")
                        .WithMany()
                        .HasForeignKey("IdClienteEsclusivo");

                    b.HasOne("PlateArchive.Core.Models.FormatoMacchina", "Formato")
                        .WithMany("Piastre")
                        .HasForeignKey("IdFormato");

                    b.Navigation("Categoria");

                    b.Navigation("ClienteEsclusivo");

                    b.Navigation("Formato");
                });

            modelBuilder.Entity("PlateArchive.Core.Models.PiastraMacchinaCompatibile", b =>
                {
                    b.HasOne("PlateArchive.Core.Models.MacchinaStandard", "MacchinaStandard")
                        .WithMany("PiastreCompatibili")
                        .HasForeignKey("IdMacchinaStandard")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PlateArchive.Core.Models.Piastra", "Piastra")
                        .WithMany("MacchineCompatibili")
                        .HasForeignKey("IdPiastra")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MacchinaStandard");

                    b.Navigation("Piastra");
                });

            modelBuilder.Entity("PlateArchive.Core.Models.Cliente", b =>
                {
                    b.Navigation("Macchine");

                    b.Navigation("Piastre");
                });

            modelBuilder.Entity("PlateArchive.Core.Models.FormatoMacchina", b =>
                {
                    b.Navigation("Macchine");

                    b.Navigation("Piastre");
                });

            modelBuilder.Entity("PlateArchive.Core.Models.MacchinaStandard", b =>
                {
                    b.Navigation("ClientiAssociati");

                    b.Navigation("PiastreCompatibili");
                });

            modelBuilder.Entity("PlateArchive.Core.Models.Piastra", b =>
                {
                    b.Navigation("ClientiAssociati");

                    b.Navigation("Disegno");

                    b.Navigation("MacchineCompatibili");
                });

            modelBuilder.Entity("PlateArchive.Core.Models.ProduttoreMacchina", b =>
                {
                    b.Navigation("Macchine");
                });
#pragma warning restore 612, 618
        }
    }
}
